### OPTION 0
NAME=Registry Run Keys
DESC=MITRE ATT&CK: T1547.001 Stealth Level: Low (but useful as decoy) Privileges Required: HKCU = user; HKLM = administrator Survives Reboot: Yes
VARS=PAYLOD_PATH: Enter the path to payload 
CMD:echo "=== HELLO option running against $TARGET_IP:$CHECK_PORT ==="
CMD:whoami
CMD:echo "The payload path is : $PAYLOAD_PATH"
### END

