#OPTION 1
#DESCRIPTION=Create a new user
#VARIABLE=admin,user,test
#COMMANDS=create_user.sh
#END

#OPTION 2
#DESCRIPTION=Delete an existing user
#VARIABLE=admin,user,test
#COMMANDS=delete_user.sh
#END

#OPTION 3
#DESCRIPTION=Check user information
#VARIABLE=admin,user
#COMMANDS=check_user.sh
#END

#OPTION 4
#DESCRIPTION=List all users
#VARIABLE=all
#COMMANDS=list_users.sh
#END
